---
# @see https://www.postgresql.org/download/linux/redhat/
# @see https://github.com/yanehi/ansible-role-patroni-centos8

- name: Install the repository RPM
  dnf:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present

- name: disable postgresql module
  shell: dnf module disable postgresql -qy
  args:
    warn: false

- name: Installed PostgreSQL packages
  dnf:
    name: "{{ pg_packages }}"
    state: present

- name: Initialize the database
  shell: sudo /usr/pgsql-{{pg_major_version}}/bin/postgresql-{{pg_major_version}}-setup initdb
  args:
    creates: /var/lib/pgsql/{{pg_major_version}}/data/postgresql.conf
    warn: false
